apiVersion: apps/v1
kind: Deployment
metadata:
  name: sports-ai-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sports-ai
  template:
    metadata:
      labels:
        app: sports-ai
    spec:
      containers:
        - name: sports-ai-container
          image: abhisheks0505/sports-ai-app:latest
          ports:
            - containerPort: 8501
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: sports-api-secret
                  key: OPENAI_API_KEY
            - name: SPORTS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: sports-api-secret
                  key: SPORTS_API_KEY
          secretKeyRef:
            name: sports-api-secret
            key: SPORTS_API_KEY